import { SparklesIcon, CheckCircleIcon, XCircleIcon } from 'lucide-react'

const valueColors = {
    Excellent: 'text-green-600 bg-green-50',
    Good: 'text-blue-600 bg-blue-50',
    Average: 'text-amber-600 bg-amber-50',
    Poor: 'text-red-600 bg-red-50',
}

const scoreBg = (score) =>
    score >= 8 ? 'bg-green-500' : score >= 6 ? 'bg-amber-500' : 'bg-red-500'

export default function AiAnalysis({ analysis }) {
    if (!analysis) return null

    return (
        <div className="border border-indigo-100 rounded-xl p-5 bg-gradient-to-br from-indigo-50/50 to-white space-y-4">
            {/* Header */}
            <div className="flex items-center justify-between">
                <div className="flex items-center gap-2 text-indigo-700 font-semibold">
                    <SparklesIcon size={18} />
                    AI Analysis
                </div>
                <div className="flex items-center gap-2">
                    <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${valueColors[analysis.valueForMoney] || 'text-slate-600 bg-slate-100'}`}>
                        {analysis.valueForMoney} value
                    </span>
                    <span className={`${scoreBg(analysis.score)} text-white text-sm font-bold w-9 h-9 rounded-full flex items-center justify-center shadow`}>
                        {analysis.score}/10
                    </span>
                </div>
            </div>

            {/* Summary */}
            <p className="text-slate-700 text-sm leading-relaxed">{analysis.summary}</p>

            {/* Pros / Cons */}
            <div className="grid sm:grid-cols-2 gap-4">
                <div>
                    <p className="text-xs font-semibold text-green-700 uppercase tracking-wide mb-2">Pros</p>
                    <ul className="space-y-1.5">
                        {analysis.pros.map((p, i) => (
                            <li key={i} className="flex items-start gap-2 text-sm text-slate-700">
                                <CheckCircleIcon size={14} className="text-green-500 shrink-0 mt-0.5" />
                                {p}
                            </li>
                        ))}
                    </ul>
                </div>
                <div>
                    <p className="text-xs font-semibold text-red-600 uppercase tracking-wide mb-2">Cons</p>
                    <ul className="space-y-1.5">
                        {analysis.cons.map((c, i) => (
                            <li key={i} className="flex items-start gap-2 text-sm text-slate-700">
                                <XCircleIcon size={14} className="text-red-400 shrink-0 mt-0.5" />
                                {c}
                            </li>
                        ))}
                    </ul>
                </div>
            </div>

            {/* Who is it for */}
            <div className="bg-white border border-slate-100 rounded-lg p-3">
                <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-1">Who is it for?</p>
                <p className="text-sm text-slate-700">{analysis.whoIsItFor}</p>
            </div>

            {/* Verdict */}
            <div className="border-t border-indigo-100 pt-3">
                <p className="text-xs font-semibold text-indigo-600 uppercase tracking-wide mb-1">Verdict</p>
                <p className="text-sm font-medium text-slate-800 italic">"{analysis.verdict}"</p>
                <p className="text-xs text-slate-400 mt-1">{analysis.scoreReason}</p>
            </div>

            <p className="text-[10px] text-slate-300">Generated by AI · Model: {analysis.model}</p>
        </div>
    )
}
