import { Stars, CheckCircle, XCircle } from 'react-bootstrap-icons'

const badgeStyle = 'text-slate-700 bg-slate-100'

export default function AiAnalysis({ analysis }) {
    if (!analysis) return null

    const summary = analysis.summary
    const pros = analysis.pros || []
    const cons = analysis.cons || []
    const whoIsItFor = analysis.whoIsItFor || analysis.who_is_it_for
    const verdict = analysis.verdict
    const score = analysis.score
    const scoreReason = analysis.scoreReason || analysis.score_reason
    const valueForMoney = analysis.valueForMoney || analysis.value_for_money
    const model = analysis.model

    return (
        <div className="border border-slate-200 rounded-xl p-5 bg-white space-y-4">
            <div className="flex items-center justify-between">
                <div className="flex items-center gap-2 text-slate-900 font-semibold">
                    <Stars size={18} />
                    AI Analysis
                </div>
                <div className="flex items-center gap-2">
                    <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${badgeStyle}`}>
                        {valueForMoney} value
                    </span>
                    <span className="bg-black text-white text-sm font-bold w-9 h-9 rounded-full flex items-center justify-center shadow">
                        {score}/10
                    </span>
                </div>
            </div>

            <p className="text-slate-700 text-sm leading-relaxed">{summary}</p>

            <div className="grid sm:grid-cols-2 gap-4">
                <div>
                    <p className="text-xs font-semibold text-slate-700 uppercase tracking-wide mb-2">Pros</p>
                    <ul className="space-y-1.5">
                        {pros.map((p, i) => (
                            <li key={i} className="flex items-start gap-2 text-sm text-slate-700">
                                <CheckCircle size={14} className="text-slate-900 shrink-0 mt-0.5" />
                                {p}
                            </li>
                        ))}
                    </ul>
                </div>
                <div>
                    <p className="text-xs font-semibold text-slate-700 uppercase tracking-wide mb-2">Cons</p>
                    <ul className="space-y-1.5">
                        {cons.map((c, i) => (
                            <li key={i} className="flex items-start gap-2 text-sm text-slate-700">
                                <XCircle size={14} className="text-slate-700 shrink-0 mt-0.5" />
                                {c}
                            </li>
                        ))}
                    </ul>
                </div>
            </div>

            <div className="bg-white border border-slate-200 rounded-lg p-3">
                <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-1">Who is it for?</p>
                <p className="text-sm text-slate-700">{whoIsItFor}</p>
            </div>

            <div className="border-t border-slate-200 pt-3">
                <p className="text-xs font-semibold text-slate-700 uppercase tracking-wide mb-1">Verdict</p>
                <p className="text-sm font-medium text-slate-800 italic">"{verdict}"</p>
                <p className="text-xs text-slate-400 mt-1">{scoreReason}</p>
            </div>

            <p className="text-[10px] text-slate-400">Generated by AI. Model: {model}</p>
        </div>
    )
}
